# Generated by Django 4.2.1 on 2023-06-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tech_used',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Technology used'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Tile'),
        ),
    ]
