# Generated by Django 4.2.1 on 2023-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tech_used_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repo',
            field=models.CharField(blank=True, max_length=85, null=True, verbose_name='Repository'),
        ),
    ]
